config/routes.rb
Rails.application.routes.draw do
  resources :quotations, only: %i[new create show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  post "/contact", to: "home#save_query"
  post "/discount", to: "home#save_discount"
  get  "/indian_tour", to: "home#indian_tour"
  get  "/quotations", to:"quotations#new"
  get  "useful_information", to:"home#useful_information"
  get  "baggage_info", to:"home#baggage_info"
  get  "airline_info", to:"home#airline_info"
  get  "airport_info", to:"home#airport_info"  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates_presence_of :name, :message => "Please provide your name. "
	#validates_presence_of :email, :message => "Please provide your email."
	validates_presence_of :phone, :message => "Please provide your phone no."
	validates_presence_of :message, :message => "Please provide your message."
	validates_presence_of :subject, :message => "Please provide your subjects."

	# validates :name, presence: true
	# validates :email, presence: true
	# validates :phone, presence: true
	# validates :message, presence: true
	# validates :subject, presence: true
end

app/models/discount.rb
class Discount < ApplicationRecord
end

app/models/mailer.rb
class Mailer < ActionMailer::Base
  include SendGrid


  def send_qatation_email_admin(contact)
    #user_name = contact.name
    #user_phone = contact.phone
    subject = "Email regarding travel plan"
    #message = contact.message
    reciever = "sukhmander.atwal@gmail.com"
    debugger
    body :contact => contact
    #mail(to: reciever, subject: subject, body: body)
  end


  #   def new_qr_user account
  #   recipients account.email
  #   bcc  'harenderymca@gmail.com'
  #   subject 'Welcome to MyiCourse'
  #   content_type "text/html"
  #   from 'myIcourse@myicourse.com'
  #   body :account => account
  # end
end  

app/models/quotation.rb
class Quotation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 skip_before_action	 :verify_authenticity_token
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def save_query
		params.permit!
		@contact = Contact.new
		@contact.name = params[:name]
		@contact.phone = params[:phone]
		@contact.subject = params[:subject]
		@contact.message = params[:message]
		
		if @contact.save
			Mailer.send_email_admin(@contact).deliver
			respond_to do |format|
        		format.html
    		end
		else
			@contact
		  	render :index
		end
	end

	def save_discount
		params.permit!
		discount = Discount.new
		discount.name = params[:name]
		discount.email = params[:email]
		if discount.save!
			render :index
		end
	end

	def indian_tour
		respond_to do |format|
        format.html
    end
  end
  
  def useful_information
  	respond_to do |format|
        format.html
    end
	end
	def baggage_info
  	respond_to do |format|
        format.html
    end
	end	
  
  def airline_info
  	respond_to do |format|
        format.html
    end
	end

	def airport_info
  	respond_to do |format|
        format.html
    end
	end		
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)
    begin
      @quotation.trip_type = params[:tripType]
      @quotation.Adult = params[:Adult].to_i
      @quotation.infants = params[:infants].to_i
      @quotation.children = params[:children].to_i
      @quotation.airlinepreference1 = params[:airlinepreference1]
      @quotation.airlinepreference2 = params[:airlinepreference2]
      @quotation.classofeconomy = params[:classofeconomy]
      @quotation.mealrequest = params[:mealrequest]
      @quotation.currency = params[:currency]
      @quotation.starttime = params[:starttime]
      @quotation.returntime = params[:returntime]
    rescue
    end  
    respond_to do |format|
      if @quotation.save
        Mailer.send_qatation_email_admin(@quotation).deliver
        format.html { redirect_to @quotation, notice: 'Your enquiry was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:start_date, :location, :return_date, :persons, :visit_purpose,:origin,:name,:phone,:email,:destination)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/home/_passport_visa_info.html.erb
<article>
    <h2 class="wrap-heading">Passport &amp; Visa Information</h2>
    <div class="pass-visa">
        <table width="100%" id="air_l">
            <tbody>
                <tr>
                    <td colspan="5" height="25">VISA INFORAMTION</td>
                </tr>
                <tr>
                    <th><a href="http://www.blsindia-canada.com/index.php" target="_blank">India</a></th>
                    <th><a href="#" target="_blank">Bangladesh</a></th>
                    <th><a href="#" target="_blank">US</a></th>
                    <th><a href="#" target="_blank">Pakistan</a></th>
                    <th><a href="#" target="_blank">United Kingdom</a></th>
                </tr>
            </tbody>
        </table>
    </div>
    <p></p>
    <div class="pass-visa">
        <table width="100%" id="air_l2" style="font-size:11px">
            <tbody>
                <tr>
                    <td width="570" height="25">PASSPORT INFORAMTION</td>
                </tr>
            </tbody>
            <tbody>
                <tr>
                    <th align="left"> </th>
                </tr>
            </tbody>
        </table>
    </div>
    <p></p>
    <div class="pass-visa">
        <table width="100%" id="air_l2" style="font-size:11px">
            <tbody>
                <tr>
                    <td height="25" colspan="2">CREDIT CARD AUTHORIZATION</td>
                </tr>
            </tbody>
            <tbody>
                <tr>
                   
                </tr>
            </tbody>
        </table>
    </div>
</article>

app/views/home/airline_info.html.erb
<div class="align-self-center w-100">
	<div class="container">
		<div class="row" style="margin-top: 12%;">
			<div style="text-align: center;">
		  	<h3 class="text-uppercase u-heading-v8__title g-font-weight-700 g-font-size-40 mb-0">
		    	<!-- <br><span class="g-color-black">PLease let us know the following details to help you :) .</span> -->
		  	</h3>

<div class="col-md-12"> 
 
 <br /><br />
</div>

			</div>	
		</div>
	</div>
</div>	

app/views/home/airport_info.html.erb
	<div class="container">
		<div class="row" style="margin-top: 20%;">
			<div class = "col-md-12">
		  		<div class = "row">
					<div class="col-md-3">
						<div class="tab">
						  <a class="tablinks" onclick="openCity(event, 'other_travel')" id="defaultOpen">Other Travel Info</a>
						  <a class="tablinks" onclick="openCity(event, 'baggage_info')">Baggage Info</a>
						  <a class="tablinks" onclick="openCity(event, 'passport_visa_info')">Passport &amp; Visa Info</a>
						  <a class="tablinks" onclick="openCity(event, 'airport_info')">Airport Info</a>
						  <a class="tablinks" onclick="openCity(event, 'airlines_info')">Airlines Info</a>
						</div>
					</div>
					<div class="col-md-9">
						<div id="other_travel" class="tabcontent">
							<%= render 'other_travel_info' %>
						</div>

						<div id="baggage_info" class="tabcontent">
						   <%= render 'baggage_info' %>
						</div>

						<div id="passport_visa_info" class="tabcontent">
						  <%= render 'passport_visa_info' %>
						</div>

						<div id="airport_info" class="tabcontent">
							<%= render 'airport_info' %>
						</div>

						<div id="airlines_info" class="tabcontent">
							<%= render 'airlines_info' %>
						</div>
					</div>
				</div>	
			</div>
		</div>
	</div>
<script>
	function openCity(evt, cityName) {
	    var i, tabcontent, tablinks;
	    tabcontent = document.getElementsByClassName("tabcontent");
	    for (i = 0; i < tabcontent.length; i++) {
	        tabcontent[i].style.display = "none";
	    }
	    tablinks = document.getElementsByClassName("tablinks");
	    for (i = 0; i < tablinks.length; i++) {
	        tablinks[i].className = tablinks[i].className.replace(" active", "");
	    }
	    document.getElementById(cityName).style.display = "block";
	    evt.currentTarget.className += " active";
	}

	// Get the element with id="defaultOpen" and click on it
	document.getElementById("defaultOpen").click();
</script>

<style type="text/css">
	.tab {
    float: left;
    display: block;
    width: 100%;
}
.tab a.active, .tab a:hover, .tab a:focus {
    border: 1px solid #f1f0f0 !important;
    position: relative;
    right: -2px;
    border-right: none !important;
    z-index: 99;
    font-weight: bold;
}

/* Style the buttons inside the tab */
.tab a {
	display: block;
	color: #000;
	margin: 0px;
	border: 1px solid #f1f0f0;
	line-height: 1.428571429;
	padding: 10px 15px;
	cursor: pointer;
}

.fee-chart table, table#air_l, .pass-visa table, .airline-site table {
    border-top: 1px solid #ebebeb;
}

.tabcontent table {
	width: 100%;
	margin-bottom: 25px;
	max-width: 100%;
    background-color: transparent;
    border-collapse: collapse;
    border-spacing: 0;
}

.tabcontent table tr th {
    font-size: 13px;
    line-height: normal;
    padding: 10px;
    background-color: rgba(204,204,204,0.4);
    border-right: 1px solid #ccc;
    text-align: center;
}

.tabcontent table tr td:first-child {
    border-left: 1px solid #ebebeb;
}
.tabcontent table tr td {
    font-size: 13px;
    line-height: normal;
    padding: 10px;
    border-right: 1px solid #ebebeb;
    text-align: center;
    border-bottom: 1px solid #ebebeb;
}

.pass-visa table tr th a, .pass-visa table tr th strong {
    color: #17459b;
}

ul#countriesList {
    padding: 0px;
    margin: 0px;
    float: left;
    width: 100%;
}

ul#countriesList li {
    list-style: none;
    padding: 10px;
    display: block;
    width: 100%;
    float: left;
    background-color: rgba(204,204,204,0.12);
    margin-bottom: 3px;
}

</style>

app/views/home/baggage_info.html.erb
<div class="align-self-center w-100">
	<div class="container">
		<div class="row" style="margin-top: 12%;">
			<div style="text-align: center;">
		  	<h3 class="text-uppercase u-heading-v8__title g-font-weight-700 g-font-size-40 mb-0">
		    	<!-- <br><span class="g-color-black">PLease let us know the following details to help you :) .</span> -->
		  	</h3>

<div class="col-md-12"> 
 <!--  -->
</div>

			</div>	
		</div>
	</div>
</div>	

app/views/home/save_query.html.erb
<div class="align-self-center w-100">
  <div class="container">
    <div class="row" style="margin-top: 12%;">
      <div style="text-align: center;">
        <h3 class="text-uppercase u-heading-v8__title g-font-weight-700 g-font-size-40 mb-0">
          <br><span class="g-color-black">We have received your response & will contact you soon . Thank you for choosing US</span>
        </h3>

      </div>  
    </div>
  </div>
</div>

app/views/home/useful_information.html.erb
<!--  -->

app/views/quotations/edit.html.erb
<h1>Editing Quotation</h1>

<%#= render 'form', quotation: @quotation %>

<%#= link_to 'Show', @quotation %> |
<%#= link_to 'Back', quotations_path %>

app/views/quotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotations</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>Location</th>
      <th>Return date</th>
      <th>Persons</th>
      <th>Visit purpose</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.start_date %></td>
        <td><%= quotation.location %></td>
        <td><%= quotation.return_date %></td>
        <td><%= quotation.persons %></td>
        <td><%= quotation.visit_purpose %></td>
        <td><%= link_to 'Show', quotation %></td>
        <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
        <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quotation', new_quotation_path %>

app/views/quotations/new.html.erb
<div class="align-self-center w-100">
	<div class="container">
		<div class="row" style="margin-top: 12%;">
			<div style="">
		  	<h3 class="text-uppercase u-heading-v8__title g-font-weight-700 g-font-size-40 mb-0">
		    	<br><span class="g-color-black">PLease let us know the following details to help you :) .</span>
		  	</h3>
				<%= render 'form', quotation: @quotation %>
				<%#= link_to 'Back', quotations_path %>
			</div>	
		</div>
	</div>
</div>	

app/views/quotations/show.html.erb
<div class="align-self-center w-100">
  <div class="container">
    <div class="row" style="margin-top: 12%;">
      <div style="text-align: center;">
        <h3 class="text-uppercase u-heading-v8__title g-font-weight-700 g-font-size-40 mb-0">
          <br><span class="g-color-black">We have received your response & will contact you soon . Thank you for choosing US</span>
        </h3>
<!--         <p>
          <strong>Start date:</strong>
          <%= @quotation.start_date %>
        </p>

        <p>
          <strong>Location:</strong>
          <%= @quotation.location %>
        </p>

        <p>
          <strong>Return date:</strong>
          <%= @quotation.return_date %>
        </p>

        <p>
          <strong>Persons:</strong>
          <%= @quotation.persons %>
        </p>

        <p>
          <strong>Visit purpose:</strong>
          <%= @quotation.visit_purpose %>
        </p> -->

      </div>  
    </div>
  </div>
</div>

<%#= link_to 'Edit', edit_quotation_path(@quotation) %> |
<%#= link_to 'Back', quotations_path %>